apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-test
  namespace: argocd
spec:
  project: default
  source: 
    # chart: trivy-operator-0.15.1
    repoURL: https://github.com/rammanoj/trivy-operator
    path: deploy/helm
    targetRevision: HEAD
    helm:
      releaseName: trivy-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  
    automated:
      selfHeal: true
      prune: true


